[_]
schema-version = "0.2"

[com.heroku.buildpacks.deb-packages]
install = [
    "gnuplot",
]

[[com.heroku.buildpacks.deb-packages.sources]]
uri = "http://ports.ubuntu.com/ubuntu-ports"
suites = ["noble"]
components = ["universe"]
arch = ["arm64"]
