name: CI
on: { pull_request: { }, push: { } }
concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  tox:
    strategy:
      fail-fast: false
      matrix:
        target: [ "ruff", "black" ]
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13
          cache: 'pip'
      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python -
      - name: Install python dependencies
        run: poetry install --with test
      - name: Run tox target
        run: poetry run tox --current-env -e ${{ matrix.target }}

  container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build container
        run: |
          # Note: we use the old build pack as we use the deployment api which doesn't support the latest
          docker run \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $PWD:/workspace -w /workspace \
            buildpacksio/pack build reviewer --builder heroku/builder:22
