name: CI
on: [ push, pull_request ]
jobs:
  pylama:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with: { python-version: '3.9' }
      - name: Install dependencies
        run: pip install pylama
      - name: Run pylama
        run: pylama cbng_trainer
