name: Copy kubernetes secrets into envvars
on: { push: { branches: [ 'main' ] }, schedule: [ {cron: '13 7 * * *'} ] }
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: cluebotng/ci-execute-fabric@48767c37face8508be96f0aeb796816197fdcf18 # main
        with:
          path: ${{ github.workspace }}/deployment
          user: cluebotng-trainer
          task: setup-secrets
          ssh_key: ${{ secrets.CI_SSH_KEY }}
