name: Release
on: { push: { branch: [ 'main' ] } }
permissions:
  deployments: write
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: cluebotng/ci-toolforge-deploy@main
        with:
          tool: cluebotng-trainer
          token: ${{ secrets.TOOLFORGE_DEPLOY_TOKEN }}
